### ISSUE TITLE
monitor.sh error

### ISSUE THREAD

**Issue by lilianwen** [FISCO-BCOS/generator#47]
master主分支
执行./monitor.sh -h显示如下错误
./monitor.sh: line 15: syntax error near unexpected token `('
./monitor.sh: line 15: `export alert_title="fisco-bcos-2.0-monitor:"(date)'

**Comment by HaoXuan40404** [comment]
已经修复，可以更细代码，使用新特性

**Comment by HaoXuan40404** [comment]
已经修复，可以拉取最新代码执行监控命令
