### ISSUE TITLE
生成的sdk证书和私钥文件名分别是node.crt和node.key，建议改成sdk.crt和sdk.key

### ISSUE THREAD

**Issue by lilianwen** [FISCO-BCOS/generator#49]
![image](https://user-images.githubusercontent.com/16525370/55375474-dc11d400-553e-11e9-8492-c265cd7c2945.png)

**Comment by HaoXuan40404** [comment]
这里的证书名字主要和web3sdk及控制台的读取逻辑有关，我们会在后续方案中修改相关的证书名称
