### ISSUE TITLE
generator --build_install_package 出错提示是错误的

### ISSUE THREAD

**Issue by lilianwen** [FISCO-BCOS/generator#51]
![image](https://user-images.githubusercontent.com/16525370/55382459-484d0180-5558-11e9-8456-94b3d03c293c.png)
如上图所示，程序提示我已经在当前目录下创建了data目录，但实际上我当前目录并没有这个目录。如下图所示：
![image](https://user-images.githubusercontent.com/16525370/55382524-6b77b100-5558-11e9-9836-6cd6eb9ea75f.png)
所以可以肯定的是，这个错误提示是错误的。

**Comment by HaoXuan40404** [comment]
当前master分支这里错误处理出现异常，develop分支已经修复，下次版本更新会修复这里的问题
